sshfs-mapper: test joining before host:port before running sshfs.
git-svn-id: https://websvn.glenux.net/svn/Upoc/sshfs-mapper/trunk@1326 eaee96b3-f302-0410-b096-c6cfd47f7835

diff --git a/sshfs-mapper b/sshfs-mapper
--- a/sshfs-mapper
+++ b/sshfs-mapper
@@ -153,6 +153,12 @@ for map_file in `find "$SSHFS_DIR" -type f -name '*.map' `; do
 	map=$( read_conf $map_file MAP )
 	echo "Map: $remote_user@$remote_host"
 
+  nc -z $remote_host $remote_port > /dev/null 2>&1
+  if [ $? != 0 ]; then
+    echo "  ERROR: can't find the server at $remote_host:$remote_port"
+    continue
+  fi
+
   map_count=0
   map_name=""
   remote_dir=""
